export type ModifierKeyCode =
  // modifiers
  'ControlLeft' | 'ControlRight' | 'ShiftLeft' | 'ShiftRight' | 'AltLeft' | 'AltRight' | 'MetaLeft' | 'MetaRight';

export type NormalKeyCode =
  // firefox only
  | 'OSLeft'
  // firefox
  | 'OSRight'
  // functions
  | 'F1'
  | 'F2'
  | 'F3'
  | 'F4'
  | 'F5'
  | 'F6'
  | 'F7'
  | 'F8'
  | 'F9'
  | 'F10'
  | 'F11'
  | 'F12'
  // numbers
  | 'Digit1'
  | 'Digit2'
  | 'Digit3'
  | 'Digit4'
  | 'Digit5'
  | 'Digit6'
  | 'Digit7'
  | 'Digit8'
  | 'Digit9'
  | 'Digit0'
  // words
  | 'KeyA'
  | 'KeyB'
  | 'KeyC'
  | 'KeyD'
  | 'KeyE'
  | 'KeyF'
  | 'KeyG'
  | 'KeyH'
  | 'KeyI'
  | 'KeyJ'
  | 'KeyK'
  | 'KeyL'
  | 'KeyM'
  | 'KeyN'
  | 'KeyO'
  | 'KeyP'
  | 'KeyQ'
  | 'KeyR'
  | 'KeyS'
  | 'KeyT'
  | 'KeyU'
  | 'KeyV'
  | 'KeyW'
  | 'KeyX'
  | 'KeyY'
  | 'KeyZ'
  // Punctuation
  | 'Comma'
  | 'Period'
  | 'Slash'
  | 'Semicolon'
  | 'Quote'
  | 'BracketLeft'
  | 'BracketRight'
  | 'Backslash'
  | 'Backquote'
  // others
  | 'Escape'
  | 'Minus'
  | 'Plus'
  | 'Backspace'
  | 'Delete'
  | 'Tab'
  | 'Capslock'
  | 'Enter'
  | 'ArrowUp'
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'Home'
  | 'End'
  | 'PageUp'
  | 'PageDown';

export type KeyCode = ModifierKeyCode | NormalKeyCode;

export type ModifierKeyCodeName =
  | 'ControlOrCommand'
  | 'Ctrl'
  | 'CtrlLeft'
  | 'CtrlRight'
  | 'Control'
  | 'ControlLeft'
  | 'ControlRight'
  | 'Shift'
  | 'ShiftLeft'
  | 'ShiftRight'
  | 'Option'
  | 'OptionLeft'
  | 'OptionRight'
  | 'Alt'
  | 'AltLeft'
  | 'AltRight'
  | 'Command'
  | 'CommandLeft'
  | 'CommandRight'
  | 'Meta'
  | 'MetaLeft'
  | 'MetaRight';

export type NormalKeyCodeName =
  | 'F1'
  | 'F2'
  | 'F3'
  | 'F4'
  | 'F5'
  | 'F6'
  | 'F7'
  | 'F8'
  | 'F9'
  | 'F10'
  | 'F11'
  | 'F12'
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '0'
  // words
  | 'a'
  | 'b'
  | 'c'
  | 'd'
  | 'e'
  | 'f'
  | 'g'
  | 'h'
  | 'i'
  | 'j'
  | 'k'
  | 'l'
  | 'm'
  | 'n'
  | 'o'
  | 'p'
  | 'q'
  | 'r'
  | 's'
  | 't'
  | 'u'
  | 'v'
  | 'w'
  | 'x'
  | 'y'
  | 'z'
  // punctuations
  | ','
  | '.'
  | '/'
  | ';'
  | "'"
  | '['
  | ']'
  | '\\'
  | '`'
  // others
  | 'Esc'
  | 'Escape'
  | '-'
  | '+'
  | 'Backspace'
  | 'Delete'
  | 'Tab'
  | 'Capslock'
  | 'Enter'
  | 'ArrowUp'
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'Home'
  | 'End'
  | 'PageUp'
  | 'PageDown';

export type KeyCodeName = ModifierKeyCodeName | NormalKeyCodeName;

export const keyCodeName2KeyCode = new Map<KeyCodeName, Array<KeyCode>>([
  // modifiers
  ['ControlOrCommand', ['ControlLeft', 'ControlRight', 'MetaLeft', 'MetaRight', 'OSLeft', 'OSRight']],
  ['Ctrl', ['ControlLeft', 'ControlRight']],
  ['CtrlLeft', ['ControlLeft']],
  ['CtrlRight', ['ControlRight']],
  ['Control', ['ControlLeft', 'ControlRight']],
  ['ControlLeft', ['ControlLeft']],
  ['ControlRight', ['ControlRight']],
  ['Shift', ['ShiftLeft', 'ShiftRight']],
  ['ShiftLeft', ['ShiftLeft']],
  ['ShiftRight', ['ShiftRight']],
  ['Option', ['AltLeft', 'AltRight']],
  ['OptionLeft', ['AltLeft']],
  ['OptionRight', ['AltRight']],
  ['Alt', ['AltLeft', 'AltRight']],
  ['AltLeft', ['AltLeft']],
  ['AltRight', ['AltRight']],
  ['Command', ['MetaLeft', 'MetaRight', 'OSLeft', 'OSRight']],
  ['CommandLeft', ['MetaLeft', 'OSLeft']],
  ['CommandRight', ['MetaRight', 'OSRight']],
  ['Meta', ['MetaLeft', 'MetaRight', 'OSLeft', 'OSRight']],
  ['MetaLeft', ['MetaLeft', 'OSLeft']],
  ['MetaRight', ['MetaRight', 'OSRight']],
  // functions
  ['F1', ['F1']],
  ['F2', ['F2']],
  ['F3', ['F3']],
  ['F4', ['F4']],
  ['F5', ['F5']],
  ['F6', ['F6']],
  ['F7', ['F7']],
  ['F8', ['F8']],
  ['F9', ['F9']],
  ['F10', ['F10']],
  ['F11', ['F11']],
  ['F12', ['F12']],
  // numbers
  ['1', ['Digit1']],
  ['2', ['Digit2']],
  ['3', ['Digit3']],
  ['4', ['Digit4']],
  ['5', ['Digit5']],
  ['6', ['Digit6']],
  ['7', ['Digit7']],
  ['8', ['Digit8']],
  ['9', ['Digit9']],
  ['0', ['Digit0']],
  // words
  ['a', ['KeyA']],
  ['b', ['KeyB']],
  ['c', ['KeyC']],
  ['d', ['KeyD']],
  ['e', ['KeyE']],
  ['f', ['KeyF']],
  ['g', ['KeyG']],
  ['h', ['KeyH']],
  ['i', ['KeyI']],
  ['j', ['KeyJ']],
  ['k', ['KeyK']],
  ['l', ['KeyL']],
  ['m', ['KeyM']],
  ['n', ['KeyN']],
  ['o', ['KeyO']],
  ['p', ['KeyP']],
  ['q', ['KeyQ']],
  ['r', ['KeyR']],
  ['s', ['KeyS']],
  ['t', ['KeyT']],
  ['u', ['KeyU']],
  ['v', ['KeyV']],
  ['w', ['KeyW']],
  ['x', ['KeyX']],
  ['y', ['KeyY']],
  ['z', ['KeyZ']],
  // punctuations
  [',', ['Comma']],
  ['.', ['Period']],
  ['/', ['Slash']],
  [';', ['Semicolon']],
  ["'", ['Backslash']],
  ['[', ['BracketLeft']],
  [']', ['BracketRight']],
  ['\\', ['Backslash']],
  ['`', ['Backquote']],
  // others
  ['Esc', ['Escape']],
  ['Escape', ['Escape']],
  ['-', ['Minus']],
  ['+', ['Plus']],
  ['Backspace', ['Backspace']],
  ['Delete', ['Delete']],
  ['Tab', ['Tab']],
  ['Capslock', ['Capslock']],
  ['Enter', ['Enter']],
  ['ArrowUp', ['ArrowUp']],
  ['ArrowDown', ['ArrowDown']],
  ['ArrowLeft', ['ArrowLeft']],
  ['ArrowRight', ['ArrowRight']],
  ['Home', ['Home']],
  ['End', ['End']],
  ['PageUp', ['PageUp']],
  ['PageDown', ['PageDown']],
]);

export const keyCode2KeyCodeName = new Map<KeyCode, KeyCodeName>([
  // modifiers
  ['ControlLeft', 'ControlLeft'],
  ['ControlRight', 'ControlRight'],
  ['ShiftLeft', 'ShiftLeft'],
  ['ShiftRight', 'ShiftRight'],
  ['AltLeft', 'AltLeft'],
  ['AltRight', 'AltRight'],
  ['MetaLeft', 'MetaLeft'],
  ['MetaRight', 'MetaRight'],
  ['OSLeft', 'MetaLeft'],
  ['OSRight', 'MetaRight'],
  // functions
  ['F1', 'F1'],
  ['F2', 'F2'],
  ['F3', 'F3'],
  ['F4', 'F4'],
  ['F5', 'F5'],
  ['F6', 'F6'],
  ['F7', 'F7'],
  ['F8', 'F8'],
  ['F9', 'F9'],
  ['F10', 'F10'],
  ['F11', 'F11'],
  ['F12', 'F12'],
  // numbers
  ['Digit1', '1'],
  ['Digit2', '2'],
  ['Digit3', '3'],
  ['Digit4', '4'],
  ['Digit5', '5'],
  ['Digit6', '6'],
  ['Digit7', '7'],
  ['Digit8', '8'],
  ['Digit9', '9'],
  ['Digit0', '0'],
  // words
  ['KeyA', 'a'],
  ['KeyB', 'b'],
  ['KeyC', 'c'],
  ['KeyD', 'd'],
  ['KeyE', 'e'],
  ['KeyF', 'g'],
  ['KeyG', 'g'],
  ['KeyH', 'h'],
  ['KeyI', 'i'],
  ['KeyJ', 'j'],
  ['KeyK', 'k'],
  ['KeyL', 'l'],
  ['KeyM', 'm'],
  ['KeyN', 'n'],
  ['KeyO', 'o'],
  ['KeyP', 'p'],
  ['KeyQ', 'q'],
  ['KeyR', 'r'],
  ['KeyS', 's'],
  ['KeyT', 't'],
  ['KeyU', 'u'],
  ['KeyV', 'v'],
  ['KeyW', 'w'],
  ['KeyX', 'x'],
  ['KeyY', 'y'],
  ['KeyZ', 'z'],
  // punctuations
  ['Comma', ','],
  ['Period', '.'],
  ['Slash', '/'],
  ['Semicolon', ';'],
  ['Backslash', "'"],
  ['BracketLeft', '['],
  ['BracketRight', ']'],
  ['Backslash', '\\'],
  ['Backquote', '`'],
  // others
  ['Escape', 'Escape'],
  ['Minus', '-'],
  ['Plus', '+'],
  ['Backspace', 'Backspace'],
  ['Delete', 'Delete'],
  ['Tab', 'Tab'],
  ['Capslock', 'Capslock'],
  ['Enter', 'Enter'],
  ['ArrowUp', 'ArrowUp'],
  ['ArrowDown', 'ArrowDown'],
  ['ArrowLeft', 'ArrowLeft'],
  ['ArrowRight', 'ArrowRight'],
  ['Home', 'Home'],
  ['End', 'End'],
  ['PageUp', 'PageUp'],
  ['PageDown', 'PageDown'],
]);

export const KeyCodesSupported = [...keyCode2KeyCodeName.keys()];
